### ISSUE TITLE
请问可以提交ts源码文件吗

### ISSUE THREAD

**Issue by Sanful** [Fun-AI-Research-Center/GoATuber#16]
当前仓库中提交的是混淆后的js，无法阅读

**Comment by lvyonghuan** [comment]
一直没管这个库了，主要是维护者都在忙别的东西去了。各有各的事情。理论上我应该收到邮件，可能我邮箱广告太多看漏了。今天回来看了眼看到这个问题（
那就顺便答一下。源码一直挂在组织里的另外一个仓库下面的。
https://github.com/Fun-AI-Research-Center/GoATuber-frontend
